### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by imnew827** [ahorner2/discord-sentiment#1]
Traceback (most recent call last):
  File "D:\discord-sentiment-main\sentiment.py", line 100, in <module>
    main()
  File "D:\discord-sentiment-main\sentiment.py", line 93, in main
    data = get_messages('1041117520704319619')
  File "D:\discord-sentiment-main\sentiment.py", line 30, in get_messages
    messages = (value['content'])  # list form
TypeError: string indices must be integers

**Comment by ahorner2** [comment]
So sorry! Just now seeing this. Threw it up on a whim. I'll get that sorted, should just need a recast. 

Thanks!
